spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/retail_pos
spring.datasource.username=postgres
spring.datasource.password=sh@r471

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080